baseURL = 'https://loco.kultura.cl/'
locale = 'es-cl'
title = 'loco'
theme = 'hugo-flex'

params:
color: black           # Any color in CSS syntax
footer: Yo lo escribo, asi que es mio. No lo uses sin permiso.
