baseURL = 'https://loco.kultura.cl/'
locale = 'es-cl'
title = 'loco'
theme = 'hugo-flex'

params:
  color: black           # Any color in CSS syntax
  divider: \2500\2500   # Any string in CSS syntax / leave empty for no divider
  footer: >-            # HTML spaces (&#32;) are needed before HTML elements
    Yo lo escribo, asi que es mio. No lo uses sin permiso.
